# set-option -sa terminal-overrides ",xterm*:Tc"

set -g mouse on 
## Mouse scroll

# Set Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
# Persist session across system restarts
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'Morantron/tmux-fingers'

set -g default-terminal "tmux-256color"

set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_window_status_style "rounded"


set -g base-index 1
set -g set-clipboard on


run '~/.tmux/plugins/tpm/tpm'

# set vi-mode
set-window-option -g mode-keys vi
set -g renumber-windows on       # renumber all windows when any window is closed

# Vim movements
# Easier pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toogle 
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind R source-file ~/.config/tmux/tmux.conf

bind-key -n C-k clear-history
 
# open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}" 
bind % split-window -h -c "#{pane_current_path}"


